default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: aqil1
  host: localhost
  port: 5433

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: module5_development

test:
  <<: *default
  database: module5_test

production:
  <<: *default
  database: module5_production
  username: module5
  password: <%= ENV["MODULE5_DATABASE_PASSWORD"] %>